### ISSUE TITLE
False reference in qmlmanager.hpp

### ISSUE THREAD

**Issue by pshobowale** [kraxarn/spotify-qt-quick#1]
I get a compile error since the settings.hpp does not exist anymore
https://github.com/kraxarn/spotify-qt-quick/blob/1b0410617dc2c9930d5e284c966f62432774fd67/src/qmlmanager.hpp#L3

**Comment by kraxarn** [comment]
Make sure you're compiling against the latest master branch and not the commit referenced from spotify-qt. It hasn't been updated yet, as spotify-qt-quick doesn't work with Qt 6 yet.

**Comment by pshobowale** [comment]
Sorry my fault. I'm gonna try it out tommorow

**Comment by kraxarn** [comment]
spotify-qt v3.4 is now released and spotify-qt-quick should now be updated and fully working again :relaxed:

**Comment by pshobowale** [comment]
Just tested it and it works again.
thanks (: +1:
