### ISSUE TITLE
Proposal: Use `qtgql` as a client library.

### ISSUE THREAD

**Issue by nrbnlulu** [kraxarn/spotify-qt-quick#7]
Hey, I am working on a graphql client for Qt-QML named [qtgql](https://github.com/qtgql/qtgql).
It aims to very easy to maintain and add/modify new features.
If you have heard on react-relay it is something similar.

I need to test it on some real project and I always thought that spotify is a great app to port to QML and graphql.
If you want to collaborate on this I would be more than happy.
Please LMK if you want more details.

**Comment by kraxarn** [comment]
Hey and sorry for the slow reply.

As this is meant as a project without any large external dependencies, with the exception of Qt, I don't feel like it fits this project very well, unless it provides some big advantage I'm not understanding as I've never used GraphQL.

**Comment by nrbnlulu** [comment]
:cool: Good luck!
 *FYI GraphQL is an API language that is ought to replace REST for Server-UI communication. *
